sudo: required

addons:
    apt:
        packages:
            - docker-ce

git: { depth: 1 }

cache: ccache

matrix:
    fast_finish: true
    include:
        -   # LINUX, Debian 9 - Stretch (stable)
            &linux
            os: linux
            language: generic
            services: docker
            env:
                - &linux-env
                    - DOCKER_IMAGE='debian'
                - DOCKER_TAG='9-slim'


        -   # LINUX, Debian 8 - Jessie (oldstable)
            <<: *linux
            env:
                - *linux-env
                - DOCKER_TAG='8-slim'

        -   # LINUX, Debian testing (rolling)
            <<: *linux
            env:
                - *linux-env
                - DOCKER_TAG='testing-slim'

        -   # OSX GCC
            &osx
            os: osx
            language: cpp
            compiler: gcc

        -   # OSX CLANG
            <<: *osx
            compiler: clang

    allow_failures:
        - env: [ *linux-env, DOCKER_TAG='testing-slim' ]
        - env: [ *linux-env, DOCKER_TAG='8-slim' ]

before_install: CI_BUILD_STEP='before_install'  .travis/travis.sh
install:        CI_BUILD_STEP='install'         .travis/travis.sh
before_script:  CI_BUILD_STEP='before_script'   .travis/travis.sh
script:         CI_BUILD_STEP='script'          .travis/travis.sh
